name: Version sync

on:
  pull_request:
    paths:
      - '**/app.json'
      - '.github/AL-Go-Settings.json'
      - '.github/workflows/version-sync.yml'

jobs:
  check:
    uses: inmindtechnologies/.github/.github/workflows/al-go-version-sync.yml@main
    with:
      app-json-path: ${{ vars.AL_APP_JSON_PATH }}
